apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: metrics
    user: speedreader
    secureJsonData:
      password: speedreader
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
