name: Release Build
# on: [push]
jobs:
  build-onnx:
    name: Build the ONNX Runtime
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        if: ${{ !env.ACT }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Sync uv
        run: cd tools && uv sync --link-mode=copy
      - name: Build Libs
        run: cd tools && uv run build.py --onnx-version 1.15.0
        # if libs updated, copy to libs/ and print a message
      - name: Install Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Build Binary
        run: dotnet publish -r linux-x64 Src/Core
      - name: Smoke Binary
        run: |
          cp Src/Core/bin/Release/net10.0/linux-x64/publish/speedread . 
          ./speedread hello.png | grep '"text": "Hello"' || exit 1
    
# have a python validatation script that validates a binary (run with only one available onnx .so so we know where it links)
