name: Dynamic Build
on: [push]
jobs:
  build:
    name: Build SpeedReader (Dynamic)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - run: git lfs pull
      - uses: ./ci/actions/dynamic-build
