name: Dynamic Build
on: [push]
jobs:
  build:
    name: Build SpeedReader (Dynamic)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: ./ci/actions/dynamic-build
